# Generated by Django 5.0.7 on 2024-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_time', models.CharField(max_length=20)),
                ('inactive_ingredient', models.TextField()),
                ('purpose', models.TextField()),
                ('keep_out_of_reach_of_children', models.TextField()),
                ('warnings', models.TextField()),
                ('when_using', models.TextField()),
                ('spl_product_data_elements', models.TextField()),
                ('warnings_and_cautions', models.TextField()),
                ('version', models.CharField(max_length=10)),
                ('dosage_and_administration', models.TextField()),
                ('stop_use', models.TextField()),
                ('spl_unclassified_section', models.TextField()),
                ('package_label_principal_display_panel', models.TextField()),
                ('indications_and_usage', models.TextField()),
                ('set_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('active_ingredient', models.TextField()),
            ],
        ),
    ]
