# Generated by Django 4.1.13 on 2024-10-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mic_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_code_category', models.CharField(max_length=100)),
                ('cpt_codes', models.CharField(max_length=100)),
                ('procedure_code_descriptions', models.TextField()),
                ('code_status', models.CharField(max_length=50)),
                ('operative_procedure', models.TextField()),
                ('procedure_description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
